============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0
rootdir: /app
plugins: cov-5.0.0, anyio-4.3.0
collected 0 items / 1 error

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_main.py ______________________
tests/test_main.py:6: in <module>
    from app.main import app
app/main.py:3: in <module>
    from app.api.main import api_router
app/api/main.py:7: in <module>
    from app.api.routes import files
app/api/routes/files.py:8: in <module>
    from app.crud import documents as crud_documents
app/crud/documents.py:6: in <module>
    from common.crud.postgres import files as crud_files
/usr/local/lib/python3.11/site-packages/common/crud/postgres/files.py:10: in <module>
    from common.postgres import engine
/usr/local/lib/python3.11/site-packages/common/postgres.py:7: in <module>
    engine = create_engine(str(settings.SQLALCHEMY_DATABASE_URI))
/usr/local/lib/python3.11/site-packages/common/config.py:57: in SQLALCHEMY_DATABASE_URI
    return MultiHostUrl.build(
E   ValueError: expected either `host` or `hosts` to be set
=============================== warnings summary ===============================
../usr/local/lib/python3.11/site-packages/pydantic/fields.py:804
  /usr/local/lib/python3.11/site-packages/pydantic/fields.py:804: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.7/migration/
    warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.11.9-final-0 -----------
Name                                                   Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------
app/__init__.py                                            0      0   100%
app/api/__init__.py                                        0      0   100%
app/api/deps.py                                           11     11     0%   4-30
app/api/main.py                                            4      2    50%   9-10
app/api/routes/files.py                                   37     34     8%   9-77
app/crud/documents.py                                     45     43     4%   7-83
app/gmail_automation/__init__.py                           0      0   100%
app/gmail_automation/generate_google_oauth2_token.py      18     18     0%   1-33
app/gmail_automation/gmail_automation_client.py          139    139     0%   1-229
app/main.py                                               25     22    12%   4-37
app/models/document_status.py                              5      0   100%
------------------------------------------------------------------------------------
TOTAL                                                    284    269     5%

=========================== short test summary info ============================
ERROR tests/test_main.py - ValueError: expected either `host` or `hosts` to b...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 3.07s ==========================
